version: '3.8'

services:
  backend:
    image: apaatlas-backend:latest
    environment:
      DATABASE_URL: sqlite:////app/backend/apa_atlas.db
    volumes:
      - ./backend/apa_atlas.db:/app/backend/apa_atlas.db:ro
      - ./backend/stats_cache.json:/app/backend/stats_cache.json:ro
      - ./data:/app/data:ro
    networks:
      - apaatlas-internal
    deploy:
      replicas: 1
      labels:
        - traefik.enable=false
      restart_policy:
        condition: any

  frontend:
    image: apaatlas-frontend:latest
    networks:
      - apaatlas-internal
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.routers.apaatlas-http.rule=Host(`apaatlas.sls.cuhk.edu.hk`)
        - traefik.http.routers.apaatlas-http.entrypoints=http
        - traefik.http.routers.apaatlas-http.middlewares=https-redirect@docker
        - traefik.http.routers.apaatlas-https.rule=Host(`apaatlas.sls.cuhk.edu.hk`)
        - traefik.http.routers.apaatlas-https.entrypoints=https
        - traefik.http.routers.apaatlas-https.tls=true
        - traefik.http.routers.apaatlas-https.tls.certresolver=le
        - traefik.http.services.apaatlas.loadbalancer.server.port=80
      restart_policy:
        condition: any

networks:
  apaatlas-internal:
    driver: overlay
  traefik-public:
    external: true
