name: apaatlas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - sqlalchemy
    - pydantic
    - pydantic-settings
    - python-multipart
    - pandas
